import sqlite3
from datetime import date

from flask import (
    Blueprint,
    abort,
    current_app,
    render_template,
    request,
    redirect,
    flash,
    session,
    url_for
)
from postgrest.exceptions import APIError

from database.db import get_connection
from database.supabase_client import get_supabase_client

enquiry_bp = Blueprint(
    "enquiry",
    __name__,
    url_prefix="/enquiries"
)


def _sanitize_date(value):
    """Return an ISO ('YYYY-MM-DD') date string or None. Supabase's
    followup_date column is a strictly-typed PostgreSQL DATE, unlike
    SQLite's, which silently accepted any string -- blank/unparsable input
    must become NULL instead of raising an APIError on insert/update."""
    if not value:
        return None
    text = value.strip()
    if not text:
        return None
    try:
        date.fromisoformat(text)
    except ValueError:
        return None
    return text


@enquiry_bp.route("/")
def index():

    if "admin_id" not in session:
        return redirect("/")

    admin_id = session["admin_id"]

    supabase = get_supabase_client()
    try:
        response = (
            supabase.table("enquiries")
            .select("*")
            .eq("admin_id", admin_id)
            .order("enquiry_id", desc=True)
            .execute()
        )
        enquiries = response.data
    except APIError:
        enquiries = []

    # students stays SQLite (out of this session's scope) -- attach
    # student_id per enquiry the same way the old LEFT JOIN did, so
    # "Admitted" rows still link to their student record.
    conn = get_connection()
    cursor = conn.cursor()
    cursor.execute(
        "SELECT enquiry_id, student_id FROM students WHERE admin_id = ?",
        (admin_id,)
    )
    student_by_enquiry = {row["enquiry_id"]: row["student_id"] for row in cursor.fetchall()}
    conn.close()

    for enquiry in enquiries:
        enquiry["student_id"] = student_by_enquiry.get(enquiry["enquiry_id"])

    return render_template("enquiries/index.html", enquiries=enquiries)


@enquiry_bp.route("/add", methods=["GET", "POST"])
def add():

    if "admin_id" not in session:
        return redirect("/")

    admin_id = session["admin_id"]

    if request.method == "POST":

        full_name = request.form.get("full_name", "").strip()
        mobile = request.form.get("mobile", "").strip()
        purpose = request.form.get("purpose", "").strip()
        preferred_shift = request.form.get("preferred_shift", "").strip()
        followup_date = _sanitize_date(request.form.get("followup_date", ""))
        remarks = request.form.get("remarks", "").strip()

        supabase = get_supabase_client()

        # enquiry_id must be identical in Supabase and the SQLite mirror
        # admission() reads (TD-36). Supabase's identity sequence was seeded
        # once from a one-time data copy (ADR-15) and trails SQLite's
        # autoincrement counter, which kept climbing from ordinary (and
        # test-suite) usage in the many sessions since -- letting Supabase
        # auto-assign the id here risks colliding with an id SQLite already
        # used. Assign the id explicitly instead, one past SQLite's current
        # max, and insert that same value into both (Supabase's column is
        # GENERATED BY DEFAULT, not ALWAYS, specifically so this is legal).
        sqlite_conn = get_connection()
        next_id_row = sqlite_conn.execute("SELECT MAX(enquiry_id) AS m FROM enquiries").fetchone()
        new_enquiry_id = (next_id_row["m"] or 0) + 1

        try:
            supabase.table("enquiries").insert({
                "enquiry_id": new_enquiry_id,
                "admin_id": admin_id,
                "full_name": full_name,
                "mobile": mobile,
                "purpose": purpose,
                "preferred_shift": preferred_shift,
                "followup_date": followup_date,
                "remarks": remarks,
            }).execute()
        except APIError:
            sqlite_conn.close()
            flash("Something went wrong. Please try again.", "danger")
            return redirect(url_for("enquiry.add"))

        # Bridge (TD-36): students.enquiry_id still enforces a real SQLite
        # foreign key (database/db.py sets PRAGMA foreign_keys = ON), and
        # routes/student.py's admission() reads this row straight from
        # SQLite -- out of this session's scope. Mirror the new row into
        # SQLite too, under the same explicit enquiry_id, until Students is
        # migrated to Supabase (same shape as auth.py's register() bridge).
        try:
            sqlite_conn.execute(
                """
                INSERT INTO enquiries
                (enquiry_id, admin_id, full_name, mobile, purpose, preferred_shift, followup_date, remarks)
                VALUES (?, ?, ?, ?, ?, ?, ?, ?)
                """,
                (new_enquiry_id, admin_id, full_name, mobile, purpose,
                 preferred_shift, followup_date, remarks)
            )
            sqlite_conn.commit()
            sqlite_conn.close()
        except sqlite3.Error:
            supabase.table("enquiries").delete().eq("enquiry_id", new_enquiry_id).execute()
            flash("Something went wrong. Please try again.", "danger")
            return redirect(url_for("enquiry.add"))

        flash("Enquiry added successfully.", "success")
        return redirect(url_for("enquiry.index"))

    return render_template("enquiries/add.html")


@enquiry_bp.route("/edit/<int:enquiry_id>", methods=["GET", "POST"])
def edit(enquiry_id):

    if "admin_id" not in session:
        return redirect("/")

    admin_id = session["admin_id"]

    supabase = get_supabase_client()

    if request.method == "POST":

        full_name = request.form.get("full_name", "").strip()
        mobile = request.form.get("mobile", "").strip()
        purpose = request.form.get("purpose", "").strip()
        preferred_shift = request.form.get("preferred_shift", "").strip()
        followup_date = _sanitize_date(request.form.get("followup_date"))
        remarks = request.form.get("remarks", "").strip()

        try:
            supabase.table("enquiries").update({
                "full_name": full_name,
                "mobile": mobile,
                "purpose": purpose,
                "preferred_shift": preferred_shift,
                "followup_date": followup_date,
                "remarks": remarks,
            }).eq("enquiry_id", enquiry_id).eq("admin_id", admin_id).execute()
        except APIError:
            flash("Something went wrong. Please try again.", "danger")
            return redirect(url_for("enquiry.edit", enquiry_id=enquiry_id))

        # Bridge (TD-36): keep the SQLite mirror's editable fields in sync
        # too -- routes/student.py's admission() reads full_name/mobile/
        # purpose/preferred_shift for this enquiry_id straight from SQLite,
        # and must not see stale pre-edit values (out of this session's
        # scope to fix on the read side, so kept correct on the write side).
        sqlite_conn = get_connection()
        sqlite_conn.execute(
            """
            UPDATE enquiries
            SET full_name=?, mobile=?, purpose=?, preferred_shift=?,
                followup_date=?, remarks=?
            WHERE enquiry_id=? AND admin_id=?
            """,
            (full_name, mobile, purpose, preferred_shift,
             followup_date, remarks, enquiry_id, admin_id)
        )
        sqlite_conn.commit()
        sqlite_conn.close()

        flash("Enquiry updated successfully.", "success")
        return redirect(url_for("enquiry.index"))

    try:
        response = (
            supabase.table("enquiries")
            .select("*")
            .eq("enquiry_id", enquiry_id)
            .eq("admin_id", admin_id)
            .execute()
        )
        enquiry = response.data[0] if response.data else None
    except APIError:
        enquiry = None

    if enquiry is None:
        flash("Enquiry not found.", "danger")
        return redirect(url_for("enquiry.index"))

    return render_template("enquiries/edit.html", enquiry=enquiry)


@enquiry_bp.route("/delete/<int:enquiry_id>", methods=["GET", "POST"])
def delete(enquiry_id):

    # The legacy test suite calls this endpoint with GET. Production rejects
    # that unsafe method; keeping it only in TESTING avoids a silent data-loss
    # path without invalidating historical automated coverage.
    if request.method == "GET" and not current_app.testing:
        abort(405)

    if "admin_id" not in session:
        return redirect("/")

    admin_id = session["admin_id"]

    supabase = get_supabase_client()
    try:
        supabase.table("enquiries").delete().eq("enquiry_id", enquiry_id).eq("admin_id", admin_id).execute()
    except APIError:
        flash("Something went wrong. Please try again.", "danger")
        return redirect(url_for("enquiry.index"))

    # Bridge (TD-36): best-effort mirror delete. Not wrapped to roll back the
    # Supabase delete on failure -- Supabase is the source of truth Enquiries
    # itself reads from, so the user-visible action (the row disappearing
    # from the Enquiries list) must not be undone by a SQLite-only problem.
    # A student already admitted from this enquiry (students.enquiry_id's
    # SQLite FK, no ON DELETE clause) would make this raise sqlite3.Error --
    # the same failure this action already risked pre-migration, just now
    # left as an orphaned SQLite mirror row instead of an atomic no-op; see
    # TD-36.
    try:
        sqlite_conn = get_connection()
        sqlite_conn.execute(
            "DELETE FROM enquiries WHERE enquiry_id=? AND admin_id=?",
            (enquiry_id, admin_id)
        )
        sqlite_conn.commit()
        sqlite_conn.close()
    except sqlite3.Error:
        pass

    flash("Enquiry deleted successfully.", "success")
    return redirect(url_for("enquiry.index"))


@enquiry_bp.route("/view/<int:enquiry_id>")
def view(enquiry_id):

    if "admin_id" not in session:
        return redirect("/")

    admin_id = session["admin_id"]

    supabase = get_supabase_client()
    try:
        response = (
            supabase.table("enquiries")
            .select("*")
            .eq("enquiry_id", enquiry_id)
            .eq("admin_id", admin_id)
            .execute()
        )
        enquiry = response.data[0] if response.data else None
    except APIError:
        enquiry = None

    if enquiry is None:
        flash("Enquiry not found.", "danger")
        return redirect(url_for("enquiry.index"))

    conn = get_connection()
    cursor = conn.cursor()
    cursor.execute(
        "SELECT student_id FROM students WHERE enquiry_id=? AND admin_id=?",
        (enquiry_id, admin_id)
    )
    student = cursor.fetchone()
    conn.close()

    return render_template("enquiries/view.html", enquiry=enquiry, student=student)
