"""
One-time migration: copy every row from the local SQLite database
(database/library.db) into the PostgreSQL schema created by
database/supabase_migration.sql on Supabase.

Run once from the project root, after supabase_migration.sql has been
executed in the Supabase SQL Editor (so every destination table exists
and is empty):

    python database/migrate_to_supabase.py

For each table, in the foreign-key-safe order defined by TABLES_IN_ORDER
(the same order supabase_migration.sql creates the tables in), this script:
  1. Checks the table actually exists in SQLite (via sqlite_master) before
     touching it -- schema.sql defines a few tables (e.g. expenses) that
     an existing library.db may predate or never have had created; a
     missing table is logged and skipped, not treated as an error.
  2. Reads every row from the SQLite table (never writes to library.db).
  3. Verifies every destination Supabase table is empty *before* importing
     anything -- if any table already has data, the whole run aborts
     without touching Supabase, to prevent duplicate imports.
  4. Sanitizes every DATE/TIMESTAMP column in memory (see TEMPORAL_COLUMNS)
     -- library.db itself is never modified, only the in-memory copy of
     each row about to be inserted. A value becomes NULL if it is empty,
     the literal string "None"/"null" (any case), or not parseable as an
     ISO date or datetime; every such correction is logged with its
     table, primary key, and column in the migration report.
  5. Inserts the (sanitized) rows into Supabase, preserving every primary
     key value exactly. This only works because schema.sql's identity
     columns are GENERATED BY DEFAULT (not GENERATED ALWAYS) AS IDENTITY,
     specifically so explicit legacy IDs can be inserted without
     OVERRIDING SYSTEM VALUE -- see docs/DECISIONS.md ADR-14.
  6. Verifies the Supabase row count now matches the SQLite row count.
     If any table fails this check, the script stops immediately --
     no further tables are imported.
  7. Resets that table's identity sequence so the *next* row Supabase
     generates continues after the highest imported ID, instead of
     colliding with a low auto-generated value.

Reads SUPABASE_URL / SUPABASE_SECRET_KEY from .env (the same variables
test_supabase.py uses) via python-dotenv.

Sequence-reset caveat: the Supabase Python client only speaks PostgREST
(HTTP) and has no endpoint for running arbitrary SQL such as
`setval(...)`. This script optionally calls a helper RPC function,
migrate_reset_identity_sequence(p_table, p_id_column, p_value), in case
one has been created in the target project. This migration does not
create that function itself (that would be a schema change). If it's
absent, the script instead prints the exact SQL to run once in the
Supabase SQL Editor at the end of the report -- data import and
verification never depend on this step succeeding.
"""

from __future__ import annotations

import argparse
import os
import sqlite3
import sys
from datetime import date, datetime
from pathlib import Path

from dotenv import load_dotenv
from postgrest import APIError
from supabase import Client, create_client

PROJECT_ROOT = Path(__file__).resolve().parent.parent
SQLITE_PATH = Path(__file__).resolve().parent / "library.db"
ENV_PATH = PROJECT_ROOT / ".env"

# (table_name, primary_key_column) in the exact order database/
# supabase_migration.sql creates the tables in -- every table only
# references tables that appear earlier in this list.
TABLES_IN_ORDER = [
    ("admins", "admin_id"),
    ("settings", "id"),
    ("enquiries", "enquiry_id"),
    ("students", "student_id"),
    ("memberships", "membership_id"),
    ("payments", "payment_id"),
    ("cashbook", "entry_id"),
    ("expenses", "expense_id"),
    ("transactions", "id"),
    ("audit_log", "log_id"),
    ("library_settings", "setting_id"),
    ("membership_settings", "setting_id"),
    ("backup_log", "log_id"),
    ("security_settings", "setting_id"),
]

# Columns typed DATE or TIMESTAMP in database/supabase_migration.sql, per
# table -- only these are sanitized. (cashbook.reference_id/source etc. and
# transactions.transaction_date are plain TEXT in the schema and are left
# untouched, matching schema.sql exactly.)
TEMPORAL_COLUMNS: dict[str, list[str]] = {
    "admins": ["created_at"],
    "settings": [],
    "enquiries": ["followup_date", "created_at"],
    "students": ["join_date", "created_at"],
    "memberships": ["joining_date", "end_date", "created_at"],
    "payments": ["payment_date", "created_at"],
    "cashbook": ["entry_date"],
    "expenses": ["expense_date", "created_at"],
    "transactions": ["created_at"],
    "audit_log": ["created_at"],
    "library_settings": ["created_at", "updated_at"],
    "membership_settings": ["created_at", "updated_at"],
    "backup_log": ["last_backup_at"],
    "security_settings": ["created_at", "updated_at"],
}

# Values that always mean "no date/timestamp", regardless of case/whitespace.
NULL_TOKENS = {"", "none", "null"}

BATCH_SIZE = 500
RESET_SEQUENCE_RPC = "migrate_reset_identity_sequence"


class MigrationError(Exception):
    """Raised to abort the migration immediately with a clear message."""


def get_sqlite_connection() -> sqlite3.Connection:
    if not SQLITE_PATH.exists():
        raise MigrationError(f"SQLite database not found at {SQLITE_PATH}")
    conn = sqlite3.connect(str(SQLITE_PATH))
    conn.row_factory = sqlite3.Row
    return conn


def get_supabase_client() -> tuple[Client, str]:
    load_dotenv(dotenv_path=ENV_PATH)
    url = os.getenv("SUPABASE_URL")
    key = os.getenv("SUPABASE_SECRET_KEY")
    if not url:
        raise MigrationError(f"SUPABASE_URL not found in {ENV_PATH}")
    if not key:
        raise MigrationError(f"SUPABASE_SECRET_KEY not found in {ENV_PATH}")
    return create_client(url, key), url


def sqlite_table_exists(conn: sqlite3.Connection, table: str) -> bool:
    cursor = conn.execute(
        "SELECT 1 FROM sqlite_master WHERE type = 'table' AND name = ?", (table,)
    )
    return cursor.fetchone() is not None


def fetch_sqlite_rows(conn: sqlite3.Connection, table: str) -> list[dict]:
    cursor = conn.execute(f"SELECT * FROM {table}")
    return [dict(row) for row in cursor.fetchall()]


def _is_valid_iso_temporal(text: str) -> bool:
    """True if text parses as an ISO date or ISO datetime."""
    try:
        date.fromisoformat(text)
        return True
    except ValueError:
        pass
    try:
        datetime.fromisoformat(text)
        return True
    except ValueError:
        return False


def sanitize_temporal_value(value):
    """Returns the cleaned value for a DATE/TIMESTAMP column: the original
    value unchanged if it's already NULL or a valid ISO date/datetime,
    otherwise None (NULL)."""
    if value is None:
        return None
    text = str(value).strip()
    if text.lower() in NULL_TOKENS:
        return None
    if _is_valid_iso_temporal(text):
        return text
    return None


def sanitize_temporal_columns(
    table: str, rows: list[dict], pk_column: str
) -> tuple[list[dict], list[tuple]]:
    """Returns (sanitized_rows, corrections). Never mutates the input rows
    (and never touches library.db) -- each correction is
    (table, pk_value, column, original_value)."""
    columns = TEMPORAL_COLUMNS.get(table, [])
    if not columns:
        return rows, []

    sanitized_rows = []
    corrections = []
    for row in rows:
        new_row = dict(row)
        for column in columns:
            if column not in new_row:
                continue
            original = new_row[column]
            cleaned = sanitize_temporal_value(original)
            if cleaned != original:
                corrections.append((table, new_row.get(pk_column), column, original))
                new_row[column] = cleaned
        sanitized_rows.append(new_row)
    return sanitized_rows, corrections


def get_remote_count(supabase: Client, table: str) -> int:
    response = supabase.table(table).select("*", count="exact", head=True).execute()
    return response.count or 0


def preflight_check(supabase: Client) -> None:
    print("Checking destination tables are empty...")
    non_empty = []
    for table, _pk in TABLES_IN_ORDER:
        try:
            count = get_remote_count(supabase, table)
        except APIError as exc:
            raise MigrationError(
                f"Could not read destination table '{table}' -- has "
                f"database/supabase_migration.sql been run in the Supabase "
                f"SQL Editor yet? ({exc})"
            ) from exc
        if count > 0:
            non_empty.append((table, count))

    if non_empty:
        lines = "\n".join(f"  - {t}: {c} existing row(s)" for t, c in non_empty)
        raise MigrationError(
            "Aborting: the following destination table(s) already contain "
            f"data -- re-running would create duplicates:\n{lines}\n"
            "Truncate them in Supabase (or restore an empty schema) before "
            "re-running this script."
        )
    print("  All destination tables are empty. Safe to proceed.\n")


def insert_rows(supabase: Client, table: str, rows: list[dict]) -> None:
    for start in range(0, len(rows), BATCH_SIZE):
        chunk = rows[start:start + BATCH_SIZE]
        try:
            supabase.table(table).insert(chunk).execute()
        except APIError as exc:
            raise MigrationError(
                f"Insert into '{table}' failed on rows "
                f"{start}-{start + len(chunk) - 1}: {exc}"
            ) from exc


def try_reset_sequence(supabase: Client, table: str, pk_column: str, max_id: int) -> bool:
    try:
        supabase.rpc(
            RESET_SEQUENCE_RPC,
            {"p_table": table, "p_id_column": pk_column, "p_value": max_id},
        ).execute()
        return True
    except APIError:
        return False


def manual_setval_sql(table: str, pk_column: str, max_id: int) -> str:
    return (
        f"SELECT setval(pg_get_serial_sequence('public.{table}', "
        f"'{pk_column}'), {max_id}, true);"
    )


def print_report(report: list[tuple]) -> None:
    print("\n=== Migration Report ===")
    header = (
        f"{'Table':<22}{'SQLite':>8}{'Supabase':>10}{'Verified':>10}"
        f"{'Sequence':>10}{'Sanitized':>11}"
    )
    print(header)
    print("-" * len(header))
    for table, sqlite_count, remote_count, verified, seq_status, corrected in report:
        print(
            f"{table:<22}{sqlite_count:>8}{remote_count:>10}"
            f"{'OK' if verified else 'FAIL':>10}{seq_status:>10}{corrected:>11}"
        )
    passed = sum(1 for r in report if r[3])
    total_corrected = sum(r[5] for r in report)
    print(f"\n{passed}/{len(report)} tables verified.")
    if total_corrected:
        print(f"{total_corrected} invalid DATE/TIMESTAMP value(s) corrected to NULL.")


def print_sanitization_log(corrections: list[tuple]) -> None:
    if not corrections:
        return
    print("\n=== Sanitization Log (corrected to NULL) ===")
    for table, pk_value, column, original in corrections:
        print(f"  {table} (pk={pk_value}) column '{column}': {original!r} -> NULL")


def run(skip_confirm: bool) -> int:
    conn = get_sqlite_connection()
    supabase, url = get_supabase_client()

    preflight_check(supabase)

    if not skip_confirm:
        answer = input(
            f"This will copy all data from database/library.db into the "
            f"Supabase project at {url}. Continue? [y/N] "
        ).strip().lower()
        if answer != "y":
            print("Aborted by user.")
            return 1

    report: list[tuple] = []
    manual_sequence_sql: list[str] = []
    all_corrections: list[tuple] = []

    for table, pk_column in TABLES_IN_ORDER:
        print(f"--- {table} ---")

        if not sqlite_table_exists(conn, table):
            print(f"Table '{table}' does not exist in SQLite — skipping.")
            report.append((table, 0, 0, True, "n/a", 0))
            continue

        rows = fetch_sqlite_rows(conn, table)
        sqlite_count = len(rows)

        if sqlite_count == 0:
            print("  No rows in SQLite -- skipping.")
            report.append((table, 0, 0, True, "n/a", 0))
            continue

        rows, corrections = sanitize_temporal_columns(table, rows, pk_column)
        if corrections:
            print(f"  Sanitized {len(corrections)} invalid DATE/TIMESTAMP value(s):")
            for _table, pk_value, column, original in corrections:
                print(
                    f"    row {pk_column}={pk_value}, column '{column}': "
                    f"{original!r} -> NULL"
                )
            all_corrections.extend(corrections)

        try:
            insert_rows(supabase, table, rows)
            remote_count = get_remote_count(supabase, table)
        except MigrationError as exc:
            report.append((table, sqlite_count, 0, False, "n/a", len(corrections)))
            print_report(report)
            print_sanitization_log(all_corrections)
            print(f"\nERROR: {exc}")
            print(
                "\nAborting immediately -- later tables were NOT imported."
            )
            return 1

        verified = remote_count == sqlite_count
        if not verified:
            report.append(
                (table, sqlite_count, remote_count, False, "n/a", len(corrections))
            )
            print_report(report)
            print_sanitization_log(all_corrections)
            print(
                f"\nERROR: '{table}' mismatch -- SQLite had {sqlite_count} "
                f"row(s), Supabase now has {remote_count}."
            )
            print(
                "\nAborting immediately -- later tables were NOT imported. "
                "Fix the discrepancy in Supabase (you will likely need to "
                "truncate this table) before re-running this script."
            )
            return 1

        max_id = max(row[pk_column] for row in rows)
        if try_reset_sequence(supabase, table, pk_column, max_id):
            seq_status = "reset"
        else:
            seq_status = "manual"
            manual_sequence_sql.append(manual_setval_sql(table, pk_column, max_id))

        report.append(
            (table, sqlite_count, remote_count, True, seq_status, len(corrections))
        )
        print(f"  Imported {sqlite_count} row(s), verified, sequence {seq_status}.")

    print_report(report)
    print_sanitization_log(all_corrections)

    if manual_sequence_sql:
        print(
            f"\nThe Supabase client cannot run raw SQL, so the following "
            f"identity sequence(s) need a one-time manual reset (no "
            f"'{RESET_SEQUENCE_RPC}' RPC found in this project). Paste this "
            f"into the Supabase SQL Editor once:\n"
        )
        print("BEGIN;")
        for statement in manual_sequence_sql:
            print(statement)
        print("COMMIT;")

    return 0


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--yes", "-y",
        action="store_true",
        help="Skip the confirmation prompt (for non-interactive runs).",
    )
    args = parser.parse_args()

    try:
        return run(skip_confirm=args.yes)
    except MigrationError as exc:
        print(f"\nERROR: {exc}", file=sys.stderr)
        return 1


if __name__ == "__main__":
    sys.exit(main())
