-- Smart Library Pro Database Schema
-- Database: PostgreSQL (Supabase)
-- Migrated from: database/schema.sql (SQLite)
--
-- Notes on translation choices:
--   * INTEGER PRIMARY KEY AUTOINCREMENT -> INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY
--     ("BY DEFAULT" instead of "ALWAYS" so existing SQLite row IDs can be inserted
--     explicitly during data migration without needing OVERRIDING SYSTEM VALUE).
--   * SQLite REAL is an 8-byte IEEE-754 float, so it maps to PostgreSQL DOUBLE PRECISION
--     (not PostgreSQL's 4-byte REAL) to preserve the same numeric precision.
--   * PRAGMA statements are removed (no PostgreSQL equivalent / not needed).
--   * All ALTER TABLE ... ADD COLUMN statements from the original file have been merged
--     into their table's CREATE TABLE definition, in the order they were added.
--   * CREATE TABLE IF NOT EXISTS is preserved exactly where the source used it, so
--     re-running this script is safe wherever the original schema intended that.

BEGIN;

-- Admins

CREATE TABLE IF NOT EXISTS admins (
    admin_id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    full_name TEXT NOT NULL,
    username TEXT NOT NULL UNIQUE,
    password TEXT NOT NULL,
    mobile TEXT NOT NULL UNIQUE,
    email TEXT,
    role TEXT DEFAULT 'admin',
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);


-- Settings

CREATE TABLE IF NOT EXISTS settings (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    library_name TEXT NOT NULL,
    owner_name TEXT,
    mobile TEXT,
    address TEXT,
    logo TEXT,
    receipt_mode TEXT DEFAULT 'auto',
    receipt_prefix TEXT DEFAULT 'RCP-',
    next_receipt_number INTEGER DEFAULT 1001
);


-- Enquiries

CREATE TABLE IF NOT EXISTS enquiries (
    enquiry_id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    admin_id INTEGER NOT NULL,
    full_name TEXT NOT NULL,
    mobile TEXT NOT NULL,
    purpose TEXT,
    preferred_shift TEXT,
    demo_done INTEGER DEFAULT 0,
    followup_date DATE,
    remarks TEXT,
    status TEXT DEFAULT 'Interested',
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (admin_id) REFERENCES admins(admin_id)
);


-- Students

CREATE TABLE IF NOT EXISTS students (
    student_id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    admin_id INTEGER NOT NULL,
    enquiry_id INTEGER,
    full_name TEXT NOT NULL,
    mobile TEXT NOT NULL,
    address TEXT,
    id_proof TEXT,
    purpose TEXT,
    shift TEXT,
    join_date DATE,
    status TEXT DEFAULT 'Active',

    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,

    UNIQUE(mobile, admin_id),

    FOREIGN KEY (admin_id) REFERENCES admins(admin_id),
    FOREIGN KEY (enquiry_id) REFERENCES enquiries(enquiry_id)
);


-- Memberships

CREATE TABLE IF NOT EXISTS memberships (
    membership_id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    student_id INTEGER NOT NULL,
    plan_name TEXT NOT NULL,
    joining_date DATE NOT NULL,
    duration_days INTEGER,
    end_date DATE NOT NULL,
    total_fee DOUBLE PRECISION NOT NULL,
    paid_amount DOUBLE PRECISION DEFAULT 0,
    pending_amount DOUBLE PRECISION DEFAULT 0,

    -- Discount (Create Membership only, ADR-46) - a staff-entered flat
    -- rupee discount is its own transparent line item, never folded
    -- silently into total_fee, so a discounted membership's history still
    -- shows what the undiscounted price was and why it was reduced.
    discount_amount DOUBLE PRECISION DEFAULT 0,
    discount_reason TEXT,

    -- Admission fee snapshot (ADR-62) - how much of this membership's
    -- total_fee, at creation, was the Membership Settings admission fee
    -- (0 for the Custom plan, or a renewal). Persisted here rather than
    -- re-read from live Settings later, so a future Settings change can
    -- never retroactively re-categorize this membership's Cashbook
    -- history. database/membership_queries.py's
    -- split_admission_and_membership_fee() uses it to divide every
    -- payment toward this membership between the "Admission Fee" and
    -- "Membership Fee" Cashbook categories, admission-fee-first.
    admission_fee_amount DOUBLE PRECISION DEFAULT 0,

    -- Idempotency (TD-30, ADR-53) - a per-page-load token the Create/Renew
    -- forms embed as a hidden field, so a double-click/back-button resubmit
    -- of the exact same rendered form hits this UNIQUE constraint instead
    -- of creating a second Active membership. NULL (no token posted, e.g.
    -- an older cached page or a direct API call) is exempt from the
    -- constraint - Postgres UNIQUE allows unlimited NULLs - so this never
    -- blocks a submission that genuinely has nothing to compare against.
    idempotency_key TEXT UNIQUE,

    remarks TEXT,
    membership_status TEXT DEFAULT 'Active',

    -- Shift slot snapshot (ADR-65) - which Settings > Shift Slots time
    -- window this membership was sold on, frozen at creation. shift_slot_id
    -- is a soft reference (no FK) because a slot is deactivated, never
    -- deleted; shift_slot_name / time_bucket are snapshots so a later slot
    -- rename / re-bucket never rewrites this membership's receipt or the
    -- Occupancy Analytics history. All three are NULL for a membership sold
    -- on a bare duration plan (the pre-ADR-65 flow, still supported).
    shift_slot_id INTEGER,
    shift_slot_name TEXT,
    time_bucket TEXT,

    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,

    FOREIGN KEY (student_id)
    REFERENCES students(student_id)
);

-- 2026-08-17 (Discount feature, ADR-46): the discount_amount/discount_reason
-- columns above are new. This script's CREATE TABLE IF NOT EXISTS only
-- applies them to a *fresh* database - an already-provisioned Supabase
-- project (this app has no direct-Postgres/psycopg2 path to run DDL from
-- Python, see ADR-14) needs this run by hand, once, in the Supabase SQL
-- Editor:
--
--   ALTER TABLE memberships
--     ADD COLUMN IF NOT EXISTS discount_amount DOUBLE PRECISION DEFAULT 0,
--     ADD COLUMN IF NOT EXISTS discount_reason TEXT;
--
-- Unlike TD-50/ADR-38's seating-capacity columns, this one does NOT
-- silently degrade if skipped: database/membership_queries.py's
-- insert_membership() raises DiscountColumnsUnavailable (caught by
-- routes/membership.py's create() with a clear flash message) rather than
-- creating a membership whose discount was silently dropped - a discount
-- is financial data, so a hard, visible failure was chosen over ADR-38's
-- silent-strip-and-retry precedent. Membership creation with no discount
-- entered (discount_amount left at 0) is unaffected either way - see
-- ADR-46.

-- 2026-08-30 (Admission Fee vs Membership Fee categorization, ADR-62):
-- admission_fee_amount above is new. Same manual-application requirement as
-- discount_amount/discount_reason above - run by hand, once, in the
-- Supabase SQL Editor:
--
--   ALTER TABLE memberships
--     ADD COLUMN IF NOT EXISTS admission_fee_amount DOUBLE PRECISION DEFAULT 0;
--
-- Like discount, this does NOT silently degrade whenever a real value would
-- be lost: database/membership_queries.py's insert_membership() raises
-- AdmissionFeeColumnUnavailable (caught by routes/membership.py's create()
-- with a clear flash message) if the membership being created has a real,
-- nonzero admission_fee_amount (a standard plan with a configured
-- Membership Settings admission fee) but this column doesn't exist yet -
-- there would be nowhere to persist which part of total_fee is the
-- admission charge, and every later payment.collect() on that membership
-- would then have no way to categorize it correctly, permanently. A
-- membership with no configured admission fee (Custom plan, or Settings'
-- admission fee is ₹0 - admission_fee_amount stays 0 either way) is
-- unaffected and inserts normally on an un-migrated project.
--
-- Before this column existed, every create()-time payment was always fully
-- categorized "Admission Fee" and every later collect()-time payment was
-- always fully categorized "Membership Fee", regardless of whether either
-- payment actually contained any real one-time admission charge. This was
-- never accurate, but it is what any Cashbook history recorded before
-- 2026-08-30 still reflects - it is not retroactively recategorized.

-- 2026-08-21 (Idempotency fix, TD-30/ADR-53): idempotency_key above is new.
-- Same manual-application requirement as every other column added after a
-- project's first provisioning (ADR-14/38/46) - run by hand, once, in the
-- Supabase SQL Editor:
--
--   ALTER TABLE memberships ADD COLUMN IF NOT EXISTS idempotency_key TEXT UNIQUE;
--
-- Unlike the discount columns, this one DOES silently degrade if skipped:
-- database/membership_queries.py's insert_membership() detects the
-- "column not found" error and retries the same insert without
-- idempotency_key, so membership creation keeps working exactly as before
-- on an un-migrated project - it just doesn't get the new double-submit
-- protection yet. See ADR-53.

-- 2026-09-02 (Time-window shift slots, ADR-65): shift_slot_id /
-- shift_slot_name / time_bucket above are new. Same manual-application
-- requirement as every other post-provisioning column (ADR-14) - run by
-- hand, once, in the Supabase SQL Editor:
--
--   ALTER TABLE memberships
--     ADD COLUMN IF NOT EXISTS shift_slot_id INTEGER,
--     ADD COLUMN IF NOT EXISTS shift_slot_name TEXT,
--     ADD COLUMN IF NOT EXISTS time_bucket TEXT;
--
-- These DO silently degrade if skipped: they are display / Occupancy
-- Analytics data only (total_fee is already correct without them), so
-- database/membership_queries.py's insert_membership() strips them and
-- retries, exactly like idempotency_key. A membership sold on a shift slot
-- on an un-migrated project just falls back to showing its plan name and
-- being bucketed by students.shift. See ADR-65.


-- Payments

CREATE TABLE IF NOT EXISTS payments (

    payment_id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,

    membership_id INTEGER NOT NULL,

    student_id INTEGER NOT NULL,

    receipt_number TEXT UNIQUE,

    payment_mode TEXT NOT NULL,

    amount_paid DOUBLE PRECISION NOT NULL,

    payment_date DATE DEFAULT CURRENT_DATE,

    remarks TEXT,

    -- Idempotency (TD-30, ADR-53) - same shape/purpose as memberships'
    -- idempotency_key above; the Collect Payment form's hidden token.
    idempotency_key TEXT UNIQUE,

    -- Cashbook sync flag (TD-43, ADR-53) - defaults TRUE; flipped to FALSE
    -- by database/payment_queries.py's record_payment() when the automatic
    -- Cashbook Income entry (database/cashbook_queries.py's
    -- insert_income_entry()) fails even after its retry, so the missing
    -- ledger row is surfaced to the admin (routes/cashbook.py) instead of
    -- silently lost. The payment itself is never rolled back for this -
    -- see ADR-53 for why.
    cashbook_synced BOOLEAN DEFAULT TRUE,

    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,

    FOREIGN KEY (membership_id)
    REFERENCES memberships(membership_id),

    FOREIGN KEY (student_id)
    REFERENCES students(student_id)

);

-- 2026-08-21 (Idempotency + cashbook-sync fix, TD-30/TD-43/ADR-53):
-- idempotency_key and cashbook_synced above are new. Same manual-application
-- requirement as every other column added after a project's first
-- provisioning (ADR-14/38/46) - run by hand, once, in the Supabase SQL
-- Editor:
--
--   ALTER TABLE payments
--     ADD COLUMN IF NOT EXISTS idempotency_key TEXT UNIQUE,
--     ADD COLUMN IF NOT EXISTS cashbook_synced BOOLEAN DEFAULT TRUE;
--
-- Both silently degrade if skipped, the same way memberships.idempotency_key
-- does: database/payment_queries.py's record_payment() detects the "column
-- not found" error and retries without the missing column(s), so payment
-- collection keeps working exactly as before on an un-migrated project - it
-- just doesn't get double-submit protection or the unsynced-cashbook banner
-- yet. See ADR-53.


-- Cashbook
-- (includes columns added later via ALTER TABLE in the SQLite source:
--  category, person, admin_id, payment_method, reference_id, source)

CREATE TABLE IF NOT EXISTS cashbook (
    entry_id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    type TEXT NOT NULL,
    description TEXT,
    amount DOUBLE PRECISION,
    entry_date DATE,
    payment_id INTEGER,
    category TEXT,
    person TEXT,
    admin_id INTEGER,
    payment_method TEXT,
    reference_id TEXT,
    source TEXT,

    FOREIGN KEY (payment_id)
    REFERENCES payments(payment_id)
);

-- expense table

CREATE TABLE expenses (

    expense_id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,

    admin_id INTEGER NOT NULL,

    title TEXT NOT NULL,

    category TEXT NOT NULL,

    amount DOUBLE PRECISION NOT NULL,

    payment_method TEXT,

    vendor TEXT,

    notes TEXT,

    expense_date DATE NOT NULL,

    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP

);

-- transaction table

CREATE TABLE IF NOT EXISTS transactions (

    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,

    transaction_type TEXT NOT NULL,

    category TEXT NOT NULL,

    person TEXT,

    amount DOUBLE PRECISION NOT NULL,

    payment_method TEXT,

    transaction_date TEXT,

    description TEXT,

    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP

);

-- Audit Trail: one row per financial change (auto or manual) to cashbook
CREATE TABLE IF NOT EXISTS audit_log (
    log_id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    admin_id INTEGER NOT NULL,
    entry_id INTEGER,
    action TEXT NOT NULL,
    details TEXT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (admin_id) REFERENCES admins(admin_id),
    FOREIGN KEY (entry_id) REFERENCES cashbook(entry_id)
);

-- Library Settings: one row per admin, holds the Settings > Library Profile form
CREATE TABLE IF NOT EXISTS library_settings (
    setting_id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    admin_id INTEGER NOT NULL UNIQUE,
    library_name TEXT NOT NULL,
    owner_name TEXT,
    phone TEXT NOT NULL,
    email TEXT,
    address TEXT,
    city TEXT,
    state TEXT,
    pincode TEXT,
    opening_time TEXT,
    closing_time TEXT,
    weekly_holiday TEXT,
    logo_path TEXT,
    stamp_path TEXT,
    signature_path TEXT,
    receipt_footer TEXT,
    receipt_prefix TEXT DEFAULT 'LIB',
    next_receipt_number INTEGER DEFAULT 1001,
    auto_increment_receipt INTEGER DEFAULT 1,
    print_logo INTEGER DEFAULT 1,
    print_stamp INTEGER DEFAULT 1,
    print_signature INTEGER DEFAULT 1,
    paper_size TEXT DEFAULT 'A4',
    auto_print INTEGER DEFAULT 0,
    auto_email INTEGER DEFAULT 0,
    open_pdf_after_save INTEGER DEFAULT 1,
    duplicate_copy INTEGER DEFAULT 0,

    -- Notification Settings (Reminder Rules)
    reminder_7_days INTEGER DEFAULT 1,
    reminder_3_days INTEGER DEFAULT 1,
    reminder_1_day INTEGER DEFAULT 1,
    notify_on_expiry_day INTEGER DEFAULT 1,
    notify_after_expiry INTEGER DEFAULT 1,

    -- Notification Settings (Channels)
    notify_in_app INTEGER DEFAULT 1,
    notify_sms INTEGER DEFAULT 0,
    notify_email INTEGER DEFAULT 0,
    notify_whatsapp INTEGER DEFAULT 0,

    -- Notification Settings (Quiet Hours)
    quiet_hours_enabled INTEGER DEFAULT 0,
    quiet_hours_start TEXT DEFAULT '22:00',
    quiet_hours_end TEXT DEFAULT '07:00',
    quiet_hours_allow_critical INTEGER DEFAULT 1,

    -- Notification Settings (Dashboard Notifications)
    dash_show_badge_count INTEGER DEFAULT 1,
    dash_show_expiry_today INTEGER DEFAULT 1,
    dash_show_expiry_tomorrow INTEGER DEFAULT 1,
    dash_show_overdue INTEGER DEFAULT 1,
    dash_show_pending_fees INTEGER DEFAULT 1,
    dash_show_new_admissions INTEGER DEFAULT 1,

    -- Seating Capacity (Settings > Library Profile; read by Occupancy
    -- Analytics, Business Intelligence Phase 3, ADR-38) - per-shift seat
    -- count this admin's library actually has, so "Available Seats"/
    -- "Occupancy %" are real capacity numbers instead of a hardcoded guess.
    morning_capacity INTEGER DEFAULT 50,
    afternoon_capacity INTEGER DEFAULT 50,
    evening_capacity INTEGER DEFAULT 50,
    -- Night seat capacity (ADR-67) - Night became a real 4th canonical shift
    -- when time-window slots (ADR-65) made a genuine night shift sellable.
    night_capacity INTEGER DEFAULT 50,

    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (admin_id) REFERENCES admins(admin_id)
);

-- 2026-07-26 (Occupancy Analytics, Phase 3, ADR-38): the three
-- morning/afternoon/evening_capacity columns above are new. This script's
-- CREATE TABLE IF NOT EXISTS only applies them to a *fresh* database - an
-- already-provisioned Supabase project (this app has no direct-Postgres/
-- psycopg2 path to run DDL from Python, see ADR-14) needs this run by hand,
-- once, in the Supabase SQL Editor:
--
--   ALTER TABLE library_settings
--     ADD COLUMN IF NOT EXISTS morning_capacity INTEGER DEFAULT 50,
--     ADD COLUMN IF NOT EXISTS afternoon_capacity INTEGER DEFAULT 50,
--     ADD COLUMN IF NOT EXISTS evening_capacity INTEGER DEFAULT 50;
--
-- Until that's run, database/settings_queries.py's create_library_settings()/
-- update_library_settings() detect the missing columns (Postgres error
-- 42703) and retry the same save without them, so Library Profile saving
-- itself never breaks - the seating-capacity fields just silently don't
-- persist yet, and Occupancy Analytics falls back to bi_queries.py's
-- DEFAULT_SHIFT_CAPACITY (50/shift) until the columns exist. See TD-49.

-- 2026-09-02 (Night as a 4th shift, ADR-67): night_capacity above is new.
-- Same manual-application requirement and same silent-degrade behaviour as
-- the morning/afternoon/evening_capacity columns:
--
--   ALTER TABLE library_settings
--     ADD COLUMN IF NOT EXISTS night_capacity INTEGER DEFAULT 50;
--
-- Until it's run, Occupancy Analytics' Night shift falls back to
-- DEFAULT_SHIFT_CAPACITY (50).

-- membership_settings Table
-- NOTE: reminder_days/send_reminders are superseded by the notification_*/
-- reminder_* columns on library_settings (Settings > Notification Settings
-- now owns reminder behaviour) - kept here unused for backward compatibility,
-- see docs/11_FUTURE_WORK.md.

CREATE TABLE IF NOT EXISTS membership_settings (
    setting_id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    admin_id INTEGER NOT NULL UNIQUE,
    monthly_fee DOUBLE PRECISION NOT NULL DEFAULT 0,
    monthly_days INTEGER NOT NULL DEFAULT 30,
    quarterly_fee DOUBLE PRECISION NOT NULL DEFAULT 0,
    quarterly_days INTEGER NOT NULL DEFAULT 90,
    half_yearly_fee DOUBLE PRECISION NOT NULL DEFAULT 0,
    half_yearly_days INTEGER NOT NULL DEFAULT 180,
    yearly_fee DOUBLE PRECISION NOT NULL DEFAULT 0,
    yearly_days INTEGER NOT NULL DEFAULT 365,
    admission_fee DOUBLE PRECISION NOT NULL DEFAULT 0,
    late_fee_per_day DOUBLE PRECISION NOT NULL DEFAULT 0,
    renewal_grace_days INTEGER NOT NULL DEFAULT 7,
    auto_expiry INTEGER NOT NULL DEFAULT 1 CHECK (auto_expiry IN (0, 1)),
    allow_early_renewal INTEGER NOT NULL DEFAULT 1 CHECK (allow_early_renewal IN (0, 1)),
    send_reminders INTEGER NOT NULL DEFAULT 1 CHECK (send_reminders IN (0, 1)),
    reminder_days INTEGER NOT NULL DEFAULT 3,

    -- Extra-charge catalog (ADR-66). Each membership charge has a fixed key
    -- with built-in semantics defined in
    -- database/membership_charges_queries.py's CHARGE_CATALOG (recurring =
    -- monthly & re-charged on renew; refundable). Here the admin configures
    -- only two things per charge: the amount, and whether it is compulsory
    -- (auto-applied to every membership) or optional (only when picked in
    -- the Create/Renew "Extra Charges" box). The "registration" charge
    -- reuses admission_fee above (same column, same ADR-62 snapshot /
    -- "Admission Fee" Cashbook category) and only adds a compulsory flag.
    seat_reservation_fee DOUBLE PRECISION NOT NULL DEFAULT 0,
    locker_fee DOUBLE PRECISION NOT NULL DEFAULT 0,
    security_deposit_amount DOUBLE PRECISION NOT NULL DEFAULT 0,
    registration_compulsory INTEGER NOT NULL DEFAULT 1 CHECK (registration_compulsory IN (0, 1)),
    seat_reservation_compulsory INTEGER NOT NULL DEFAULT 0 CHECK (seat_reservation_compulsory IN (0, 1)),
    locker_compulsory INTEGER NOT NULL DEFAULT 0 CHECK (locker_compulsory IN (0, 1)),
    security_deposit_compulsory INTEGER NOT NULL DEFAULT 1 CHECK (security_deposit_compulsory IN (0, 1)),

    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (admin_id) REFERENCES admins(admin_id)
);

-- 2026-09-02 (Membership extra charges, ADR-66): the seven columns above
-- (seat_reservation_fee, locker_fee, security_deposit_amount, and the four
-- *_compulsory flags) are new. Same manual-application requirement as every
-- other post-provisioning column (ADR-14) - run by hand, once, in the
-- Supabase SQL Editor:
--
--   ALTER TABLE membership_settings
--     ADD COLUMN IF NOT EXISTS seat_reservation_fee DOUBLE PRECISION NOT NULL DEFAULT 0,
--     ADD COLUMN IF NOT EXISTS locker_fee DOUBLE PRECISION NOT NULL DEFAULT 0,
--     ADD COLUMN IF NOT EXISTS security_deposit_amount DOUBLE PRECISION NOT NULL DEFAULT 0,
--     ADD COLUMN IF NOT EXISTS registration_compulsory INTEGER NOT NULL DEFAULT 1,
--     ADD COLUMN IF NOT EXISTS seat_reservation_compulsory INTEGER NOT NULL DEFAULT 0,
--     ADD COLUMN IF NOT EXISTS locker_compulsory INTEGER NOT NULL DEFAULT 0,
--     ADD COLUMN IF NOT EXISTS security_deposit_compulsory INTEGER NOT NULL DEFAULT 1;
--
-- These silently degrade if skipped: database/membership_settings_queries.py's
-- save_membership_settings() strips them and retries (ADR-38 precedent), and
-- get_charge_config() falls back to built-in defaults (all fees 0), so no
-- charge is ever applied until the columns exist and an admin sets an
-- amount. See ADR-66.

-- Data & Backup: one row per admin, tracks the last manual backup taken.
-- Kept separate from library_settings because a backup can be taken before
-- a Library Profile row exists (library_settings.library_name/phone are
-- NOT NULL, so it can't hold a lazily-created bare row).
CREATE TABLE IF NOT EXISTS backup_log (
    log_id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    admin_id INTEGER NOT NULL UNIQUE,
    last_backup_at TIMESTAMP,
    backup_filename TEXT,
    FOREIGN KEY (admin_id) REFERENCES admins(admin_id)
);

-- Security Settings: one row per admin. Kept separate from library_settings
-- for the same reason as backup_log.
CREATE TABLE IF NOT EXISTS security_settings (
    setting_id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    admin_id INTEGER NOT NULL UNIQUE,
    session_timeout_minutes INTEGER NOT NULL DEFAULT 60,
    remember_me_enabled INTEGER NOT NULL DEFAULT 0 CHECK (remember_me_enabled IN (0, 1)),
    login_notifications_enabled INTEGER NOT NULL DEFAULT 0 CHECK (login_notifications_enabled IN (0, 1)),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (admin_id) REFERENCES admins(admin_id)
);

-- AI Center Settings: one row per admin. The weights/thresholds
-- database/ai_center_queries.py's retention-risk scoring engine reads
-- (ADR-40) - kept separate from library_settings for the same reason as
-- Security/Membership Settings. Weights are integer percentages of the
-- three scoring signals (payment delay, renewal history, membership
-- duration) and are expected to sum to 100 - enforced at the application
-- layer (routes/ai_center.py's settings()), not a DB CHECK constraint,
-- since Supabase/PostgREST here has no cross-column CHECK support reachable
-- from this app's migration workflow (same reasoning as ADR-14/38).
--
-- NOTE: this is a brand-new table, not an ALTER TABLE on an existing one -
-- same manual-application requirement as ADR-38's *_capacity columns (this
-- app has no exec_sql/DDL RPC and no direct-Postgres path, ADR-14). Until
-- an existing Supabase project's owner runs this CREATE TABLE by hand in
-- the SQL Editor, database/ai_center_settings_queries.py's reads degrade to
-- DEFAULTS (verified live: PostgREST raises PGRST205 "Could not find the
-- table" until it exists) and its writes raise postgrest.exceptions.
-- APIError, caught by routes/ai_center.py's settings() to flash a clear
-- message instead of a 500.
CREATE TABLE IF NOT EXISTS ai_center_settings (
    setting_id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    admin_id INTEGER NOT NULL UNIQUE,
    weight_payment_delay INTEGER NOT NULL DEFAULT 45,
    weight_renewal_history INTEGER NOT NULL DEFAULT 35,
    weight_membership_duration INTEGER NOT NULL DEFAULT 20,
    high_risk_max INTEGER NOT NULL DEFAULT 40,
    low_risk_min INTEGER NOT NULL DEFAULT 70,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (admin_id) REFERENCES admins(admin_id)
);

-- Panda AI Assistant: conversation + message history for the floating chat
-- widget (`panda/` blueprint package, ADR-43). This phase deliberately ships
-- no real LLM (see panda/prompts.py's generate_placeholder_reply) - these
-- two tables exist purely so multi-conversation chat history already works
-- end-to-end and doesn't need a schema change the day a real model is wired
-- in. One admin can own many conversations; one conversation owns many
-- messages, oldest first.
--
-- NOTE: brand-new tables, same manual-application requirement as
-- ai_center_settings above (this app has no DDL path, ADR-14/38). Until an
-- existing Supabase project's owner runs this CREATE TABLE by hand in the
-- SQL Editor, database/panda_queries.py's reads/writes raise
-- ChatStorageUnavailable (verified live pattern: PostgREST raises PGRST205
-- "Could not find the table" until it exists), caught by panda/routes.py to
-- return a 503 with a clear message instead of a 500 - the floating button,
-- Today's AI Insights, and Suggested Questions all still work with no chat
-- history storage, since none of those read these tables.
CREATE TABLE IF NOT EXISTS panda_conversations (
    conversation_id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    admin_id INTEGER NOT NULL,
    title TEXT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (admin_id) REFERENCES admins(admin_id)
);

CREATE TABLE IF NOT EXISTS panda_messages (
    message_id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    conversation_id INTEGER NOT NULL,
    role TEXT NOT NULL CHECK (role IN ('user', 'assistant')),
    content TEXT NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (conversation_id) REFERENCES panda_conversations(conversation_id)
);

-- Shift Slots (ADR-65): the admin-defined list of time-window shifts a
-- library sells memberships on (Settings > Shift Slots). One row per slot,
-- one admin owns many. start_time NULL means "any time" (Full Day, or a
-- split/flexi slot with no single start); time_bucket NULL means "derive
-- Morning/Afternoon/Evening/Night from start_time"
-- (database/membership_queries.py's derive_time_bucket), a non-NULL value
-- is the admin's explicit override. hours_label ('Full Day' | '7' | '4' |
-- 'Night-hourly' | 'Custom') is a price/label hint only - it never affects
-- the bucket. is_night_hourly slots are billed night_hourly_rate x
-- staff-entered hours instead of monthly_fee x plan term.
--
-- NOTE: brand-new table, same manual-application requirement as
-- ai_center_settings / panda_* above (this app has no DDL path, ADR-14/38/40).
-- Until an existing project's owner runs this CREATE TABLE by hand in the
-- SQL Editor, database/shift_slots_queries.py's reads return [] (PostgREST
-- raises PGRST205 until the table exists) so the Create/Renew shift
-- dropdown is simply hidden and the 5 fixed duration plans keep working
-- unchanged; its writes raise APIError, caught by routes/setting.py to
-- flash a clear message instead of a 500.
CREATE TABLE IF NOT EXISTS shift_slots (
    slot_id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    admin_id INTEGER NOT NULL,
    name TEXT NOT NULL,
    start_time TIME,
    end_time TIME,
    hours_label TEXT NOT NULL DEFAULT 'Custom',
    monthly_fee DOUBLE PRECISION NOT NULL DEFAULT 0,
    time_bucket TEXT,
    is_night_hourly INTEGER NOT NULL DEFAULT 0 CHECK (is_night_hourly IN (0, 1)),
    night_hourly_rate DOUBLE PRECISION NOT NULL DEFAULT 0,
    active INTEGER NOT NULL DEFAULT 1 CHECK (active IN (0, 1)),
    sort_order INTEGER NOT NULL DEFAULT 0,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UNIQUE(admin_id, name),
    FOREIGN KEY (admin_id) REFERENCES admins(admin_id)
);

-- Membership Charges (ADR-66): one row per extra charge actually applied to
-- a membership (seat reservation, locker, security deposit - "registration"
-- stays on memberships.admission_fee_amount and is not duplicated here).
-- amount is the term total already folded into memberships.total_fee (a
-- recurring charge is amount-per-month x plan months); label / recurring /
-- refundable are snapshots of CHARGE_CATALOG at creation so a later catalog
-- change never rewrites history. refunded_on is stamped by
-- routes/membership.py's refund_charge() when a refundable charge (deposit)
-- is returned.
--
-- NOTE: brand-new table, same manual-application requirement as shift_slots
-- above. Until it exists, database/membership_charges_queries.py's reads
-- return [] and insert_membership_charges() raises ChargeTableUnavailable
-- if any charge with a non-zero amount would be lost (caught by
-- routes/membership.py's create() - the membership row it just inserted is
-- deleted and a clear message is flashed, nothing half-saved); a membership
-- with no extra charge configured is unaffected. See ADR-66.
CREATE TABLE IF NOT EXISTS membership_charges (
    charge_id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    membership_id INTEGER NOT NULL,
    charge_key TEXT NOT NULL,
    label TEXT NOT NULL,
    amount DOUBLE PRECISION NOT NULL DEFAULT 0,
    recurring INTEGER NOT NULL DEFAULT 0 CHECK (recurring IN (0, 1)),
    refundable INTEGER NOT NULL DEFAULT 0 CHECK (refundable IN (0, 1)),
    refunded_on DATE,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UNIQUE(membership_id, charge_key),
    FOREIGN KEY (membership_id) REFERENCES memberships(membership_id)
);

COMMIT;
